---
name: bash_unit

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  shellcheck:
    name: bash_unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run bash_unit
        run: |
          make test
