---
name: Tests

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  bash_unit:
    name: bash_unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run bash_unit
        run: |
          make test
